### ISSUE TITLE
swanvis broken?

### ISSUE THREAD

**Issue by rsalz** [mortazavilab/swan_vis#10]
Hi
I've been an extremely satisfied user of swanvis up until now. The last time I used it was in mid-January, about 6 months ago. I tried to use it again now and it seems to be broken? 
I tried to re-install with pip and the installation failed, i used 'pip3' like another user stated in another issue and that did run to completion, but when trying to import into python itself the package couldn't be found. 
I cloned the repository and installed it with 'pip3 install .'. That worked and I was able to load the package into python. but then i ran 'sg = swan.SwanGraph()' and got "AttributeError: module 'swan_vis' has no attribute 'SwanGraph'"!! What gives??

ETA: Python 3.7.6 in a conda env

**Comment by fairliereese** [comment]
Oh no! I'm so sorry that this happened. Looking at the commit log to master there really shouldn't have been anything pushed that would cause such a problematic error (except for a Python version requirement change, which the version you're running satisfies), and I'm able to import and initialize a SwanGraph using the following code without getting the same errors that you did. 

```python
import swan_vis as swan
sg = swan.SwanGraph()
```

To replicate your situation I used the following steps:

- Created a fresh conda environment with Python version 3.7.6
- Cloned the most recent master commits for swan_vis
- Used `pip3 install -e .` in the `swan_vis` main directory to install it

Maybe it's worth trying these steps using a fresh conda environment to see if that's able to get it to work. If that doesn't work I'd love to keep working with you to get it up and running again.

**Comment by rsalz** [comment]
Ah set up a fresh conda environment and it works again! Thanks for your help!

**Comment by fairliereese** [comment]
Yay! Thanks for giving that a try!
