### ISSUE TITLE
Intron retention and exon skipping analysis

### ISSUE THREAD

**Issue by rsalz** [mortazavilab/swan_vis#11]
Hi
This is more of a recommendation than an issue. I'm really interested in intron retention and exon skipping for my research and I find it a bit confusing how this analysis is set up in swanvis now. By running `ir_genes, ir_transcripts, ir_edges = sg.find_ir_genes()` as is in the tutorial, you get 3 lists that you actually cannot easily relate to one another. For any particular tuple in the ir_edges list, there is no way for me to know which transcript or gene it is associated to. Would it not make more sense to have as output a pandas dataframe with 3 columns (gene, transcript, edge) instead of 3 lists?
Thanks for hearing me out!

**Comment by fairliereese** [comment]
This sounds like a great idea! I'll try to roll it into the next update which should be coming within the next month or so.

**Comment by fairliereese** [comment]
Solved with https://github.com/mortazavilab/swan_vis/commit/4fcf8c4b69ee3a6c8f37ea2358b76ec321f4a4c3

**Comment by fairliereese** [comment]
Hi there! This has been patched in v2.0!

**Comment by rsalz** [comment]
Great! Now there are edge IDs. How can I connect the edge IDs to actual genomic coordinates?

**Comment by fairliereese** [comment]
Hi! The best way to do this would be to merge the genomic locations in from the location DataFrame in the SwanGraph. I've included some code to do so below. Check out the [documentation](https://freese.gitbook.io/swan/faqs/data_structure) on how the data is stored in the SwanGraph as well for details on why this works.

```bash
sg = <your SwanGraph>
edge_info = sg.edge_df.merge(sg.loc_df[['chrom', 'coord']],
			how='left', left_on='v1', right_on='vertex_id')
edge_info.rename({'coord': 'start'}, axis=1, inplace=True)
edge_info = edge_info.merge(sg.loc_df[['coord']],
			how='left', left_on='v2', right_on='vertex_id')
edge_info.rename({'coord': 'stop'}, axis=1, inplace=True)
edge_info.drop(['v1', 'v2'], axis=1, inplace=True)
```

**Comment by fairliereese** [comment]
Hey, apologies for the delay. The changes have been made on the master branch. 

Note: If you're planning on running `die_gene_test()` with this version, the outputs have changed but are not documented yet - basically it now returns two dataframes, the first of which will be your normal results and the second of which tells you whether or not the gene was testable and why, so I'd recommend changing your calls to this function to something like the following:

```python
die_table, test_results = sg.die_gene_test(<options>)
```

**Comment by rsalz** [comment]
> > Also, the differential isoform expression output is changed in the new version. It now gives the genes that are changed per condition but no longer tells _which_ isoforms were switched. Why did you decide to change that? I have different conditions where there are DIE genes in common.. but no information about the particular isoforms that were switched, which may be different per condition
> 
> The underlying framework for the isoform switching tests has changed drastically! You can see details [here](https://freese.gitbook.io/swan/tutorials/analysis_tools#isoform-switching-differential-isoform-expression-testing). Adding the isoforms that are used to calculate the DPI values between conditions would certainly be useful and I will plan on doing so in a future release. However in the interim, I recommend plotting the gene reports in Swan for your isoform switching genes using the "pi" layer (given as in example in [this section](https://freese.gitbook.io/swan/tutorials/visualization#swan-reports)) to see what is driving your called switches.

Hi so have you been able to do this yet? I would like to know which isoforms exactly were involved in isoform switching, more specifically, what domains/functions were included/left out in these switiches. I am doing this on a whole-transcriptome level so I will not plot gene reports for every gene. Do you have any suggestions of how I can get this info?

**Comment by fairliereese** [comment]
Hi, 
I have not gotten around to this yet. It is still on my list! I'm sorry for the delay.

**Comment by fairliereese** [comment]
Hi there! Newest commits to master should report the isoforms used to calculate each gene's DPI in the same output table! Please let me know if it works for you :)

**Comment by rsalz** [comment]
> Hi there! Newest commits to master should report the isoforms used to calculate each gene's DPI in the same output table! Please let me know if it works for you :)

I tried and it didn't work :/ the table looks the same as before.
what I tried: cloned the repository, cd into repository and pip installed
made a new swan graph just in case, input my data and ran the same commands as I always do e.g. `sg.die_gene_test`

Is there a new option I have to toggle to get the isoform names in the table?

**Comment by fairliereese** [comment]
Hey, 

Firstly, did you make sure to run `pip install .` and not `pip install swan_vis` when installing the latest commits?

If the above is not a problem, I'm wondering if the install didn't write files to the right place for your environment to find the newest commits. In your python terminal or notebook where you're using Swan, can you run:


```python
import swan_vis as swan

print(swan.__file__)
```

Use the file path that is output to try to see in bash when the last time the file was updated to check that where your environment is looking includes the new installation:

```bash 
ls -lt <output path>
```

If you see that the modified date is earlier than when you redownloaded it, then something went wrong.
