### ISSUE TITLE
Missing transcripts

### ISSUE THREAD

**Issue by rsalz** [mortazavilab/swan_vis#14]
It seems that some transcripts that are present in 'all_talon_abundance_filtered.tsv' and 'all_talon_observedOnly.gtf' are not in the swangraph object when I upload them. How could this be? Is there an additional filtering that filters out transcripts while I add them?

More specifically- I have 6,070 of 12,812 novel transcripts remaining after I upload them into the swan object.

I'm using the standard `sg.add_transcriptome(talon_db, pass_list=pass_list)` and `sg.add_abundance(ab_file)` as you suggest in the tutorial

**Comment by fairliereese** [comment]
Hi there, 
Swan's `add_transcriptome()` function has an argument `include_isms` whose default value is False. (Documented here: https://freese.gitbook.io/swan/code-documentation/swangraph). Internally our group typically does not analyze ISM (incomplete splice match) transcripts as they are both numerous and dubious. If you wish to keep them in your analyses please just use `include_isms=True` when you're initializing your SwanGraph!

**Comment by rsalz** [comment]
That helped a lot. Unfortunately that didn't fix it completely. It seems some transcripts have the wrong edge IDs associated with them in `sg.t_df`. For example, I have the following 2 lines in my GTF:

```
chr10   TALON   transcript      102812651       102816267       .       +       .       gene_id "ENSG00000166272.17"; transcript_id "novelT000306104"; gene_name "WBP1L"; gene_status "KNOWN"; gene_type "protein_coding"; transcript_status "NOVEL"; transcript_name "novelT000306104"; talon_gene "30015"; talon_transcript "306104"; ISM_to_IDs "306002"; ISM_transcript "TRUE";
chr10   TALON   exon    102812651       102816267       .       +       .       gene_id "ENSG00000166272.17"; transcript_id "novelT000306104"; gene_type "protein_coding"; gene_status "KNOWN"; gene_name "WBP1L"; transcript_status "NOVEL"; transcript_name "novelT000306104"; exon_number "1"; exon_id "1073845"; talon_gene "30015"; talon_transcript "306104"; talon_exon "1073845"; exon_status "NOVEL";
```

When I cross reference the 2 edge ids in `loc_path` for transcript novelT000306104, I get 2 exons in chr2, completely different coordinates. Abundance is also wrong.
Tried importing TALON db or GTF but problem exists for both. 

Backstory of how I found this: I sum exon counts and compare them to individual transcript counts at a particular genomic coordinate. Exon counts must be equal to or greater than transcript counts. This check fails multiple times in my dataset. What I wrote above is just one example

**Comment by fairliereese** [comment]
> ***EDIT: figured out I should be looking at 'path' not 'loc_path', my bad!!** Thanks!

I had a feeling this was the case! Good detective work!
