### ISSUE TITLE
AttributeError: 'SwanGraph' object has no attribute 'ass_transcriptome'

### ISSUE THREAD

**Issue by xiaonalu** [mortazavilab/swan_vis#15]
Hi,
I basically ran the script as the website presents. while I received below error. Any idea to solve it? Thanks

Adding annotation to the SwanGraph
Traceback (most recent call last):
  File "/Swan/Swan.py", line 24, in <module>
    sg.ass_transcriptome(data_gtf)
AttributeError: 'SwanGraph' object has no attribute 'ass_transcriptome'

**Comment by fairliereese** [comment]
Hi, 
Looks like you just spelled the function name incorrectly. It should be`add_transcriptome`.

**Comment by xiaonalu** [comment]
sorry...my bad...
