### ISSUE TITLE
replace talon.db

### ISSUE THREAD

**Issue by xiaonalu** [mortazavilab/swan_vis#16]
Hello,
I have my data preprocessed using SQANIT3. I was wondering if I don't want to use the talon.db, what data from SQANTI3 could replace it? If I don't need the quantification, but only the visualization of my transcripts, is it still necessary? Thanks
Best
Xiaona

**Comment by fairliereese** [comment]
Swan is able to handle GTFs as input for transcript ones. You should be
able to use the one that's output from SQANTI. If that gives you any
trouble please let me know.

**Comment by fairliereese** [comment]
Please look at this section of the documentation: https://freese.gitbook.io/swan/tutorials/getting_started#adding-transcript-models-from-a-gtf

**Comment by xiaonalu** [comment]
Thank you for the tutorial. There is still an issue regarding the "merge on int64" as below

Traceback (most recent call last):
  File "/Swan/Swan.py", line 24, in <module>
    sg.add_abundance(ab_file)
  File "/conda_envs/swan/lib/python3.9/site-packages/swan_vis/swangraph.py", line 276, in add_abundance
    df = df.merge(self.t_df['tid'].to_frame(), how='right', left_on='tid', right_index=True)
  File "/conda_envs/swan/lib/python3.9/site-packages/pandas/core/frame.py", line 9191, in merge
    return merge(
  File "/conda_envs/swan/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 105, in merge
    op = _MergeOperation(
  File "/conda_envs/swan/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 702, in __init__
    self._maybe_coerce_merge_keys()
  File "/conda_envs/swan/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1255, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat

**Comment by fairliereese** [comment]
Can you send me a screenshot of your abundance file please?

**Comment by xiaonalu** [comment]
Yes. Thank you
<img width="179" alt="Screen Shot 2021-12-10 at 1 51 23 PM" src="https://user-images.githubusercontent.com/89666046/145626399-f6772486-b746-4dfd-9bbd-563767c5c2d2.png">

**Comment by fairliereese** [comment]
Can you also please send me a couple of lines of your GTF? It seems like you might have mismatches between the transcript IDs reported in your GTF and reported in your abundance matrix.

**Comment by xiaonalu** [comment]
Could this link work for you?https://drive.google.com/drive/folders/1mxvjWqdYfzzdTNJPP9aOiJHnnFoWwMNv?usp=sharing
Thanks a lot

**Comment by fairliereese** [comment]
Nope, I don't have access to that. Just the first few lines copied here should work.

**Comment by xiaonalu** [comment]
Thank you
chr15 PacBio transcript 89383787 89432079 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89383787 89384122 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89384418 89384621 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89385607 89385678 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89387323 89387431 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89387506 89387657 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89387743 89387910 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89388000 89388116 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89388520 89388597 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89389593 89389659 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89405306 89405576 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89408229 89408422 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89409363 89409476 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89415546 89415621 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89415829 89415911 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89416298 89416422 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89416532 89416664 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89417577 89417657 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89422218 89422241 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89427303 89427433 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89427997 89428081 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio exon 89431829 89432079 . + . transcript_id "PB.13560.221"; gene_id "PB.13560.221";
chr15 PacBio transcript 89383790 89417657 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89383790 89384122 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89384418 89384621 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89385607 89385678 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89387323 89387431 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89387506 89387657 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89387743 89387910 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89388000 89388116 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89388520 89388597 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89389593 89389659 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89405306 89405576 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89408229 89408422 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89409363 89409476 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89415546 89415621 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89415829 89415911 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89416449 89416664 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
chr15 PacBio exon 89417577 89417657 . + . transcript_id "PB.13560.226"; gene_id "PB.13560.226";
________________________________

**Comment by xiaonalu** [comment]
Hello, I think I made a figure out. The gene summary one. Is there a way to check whether it's correct? Thanks
Best
Xiaona
________________________________

**Comment by xiaonalu** [comment]
I figure out the reason of that error I think. When SQANTI3 generate the abundance matrix, the third column is p value. I removed it using excel, when I forgot to change the format. When I use the corrected tab separate file, the problem solved. Thank you so much for the wonderful script. The figure is very beautiful.

**Comment by fairliereese** [comment]
Oh perfect, glad it worked for you! Please don't hesitate to ask if you have any more questions :)
