### ISSUE TITLE
relation between splicing in/out sites and exons 

### ISSUE THREAD

**Issue by xiaonalu** [mortazavilab/swan_vis#18]
Hi,
I was wondering if there is a tabular info of the relation between splicing in/out sites and exons of genes. It will be very helpful when the gene is very long. Thanks

**Comment by fairliereese** [comment]
Hi, 

I'm not entirely sure what you're referring to but you might try the following function [`get_edge_abundance`](https://github.com/mortazavilab/swan_vis/blob/5cc178ee664732b87272756337e31bc388e63c99/swan_vis/swangraph.py#L1869), which will return a DataFrame detailing what the coordinates of each edge (intron or exon) are. Is this what you're looking for?

**Comment by xiaonalu** [comment]
Many Thanks. This is what I need, while I still have the no attribute error happen again. Will you suggest I uninstall and reinstall everything? Thanks
Best
Xiaona
________________________________

**Comment by xiaonalu** [comment]
Umm... It shows as below 
Read in graph from data/swan.p
Traceback (most recent call last):
  File "/Swan/Swan_quantification.py", line 16, in <module>
    df = sg.get_edge_abundance(kind='tpm', prefix='test')
  File "/conda_envs/swan/lib/python3.9/site-packages/swan_vis/swangraph.py", line 1853, in get_edge_abundance
    columns = self.edge_adata.var.index.tolist()
AttributeError: 'SwanGraph' object has no attribute 'edge_adata'

Thank you

**Comment by fairliereese** [comment]
Ah, I suggest you follow the installation instructions to install from
GitHub. This function is relatively new and hasn't been added to the pip
release yet.

**Comment by xiaonalu** [comment]
Got it. Thank you very much
Best
Xiaona
________________________________
