### ISSUE TITLE
self.create_dfs_db(fname, annot, whitelist, 'hepg2_1')

### ISSUE THREAD

**Issue by ashokpatowary** [mortazavilab/swan_vis#4]
Hi @fairliereese 

Its a really nice package. I was looking for such visualization and switcinging tool for some. However, I am having some issues. I am having an error and I am trying to use talon database. Its mainly an error for not finding hepg2_1 in database. I think its because of the following line. Can you look into it?

`self.create_dfs_db(fname, annot, whitelist, 'hepg2_1')`

**Comment by fairliereese** [comment]
Hi there, I'm glad you are interested in using Swan! I'm so sorry, this line totally looks like I edited it in internal testing and somehow I forgot to remove it. I'll push a new release with the corrected code as soon as possible.

**Comment by fairliereese** [comment]
The new version is up! You can reinstall it from pip. It should work for you now.
