### ISSUE TITLE
Novelty info not found 

### ISSUE THREAD

**Issue by SziKayLeung** [mortazavilab/swan_vis#9]
Hello Fairlie, 

Thank you for the swan package - love the visualisations! I just had a question regarding the novel splice junctions visualisation, as the warning message "Novelty info not found for x. Transcripts without novelty information will be labelled "Undefined" appears every time I add a dataset.

I am using the mouse reference genome gtf as annotation gtf and my Iso-Seq gtf output from SQANTI as the dataset input (bypassing TALON). 

Is the novelty aspect documented in the gtf or is there a specific file I need to include? Any guidance on this will be greatly appreciated! 

Thank you, 
Szi Kay

**Comment by SziKayLeung** [comment]
Hello @fairliereese, 

Thank you for the prompt reply - the code works really well I have successfully annotated the novelty aspect from SQANTI. 
I will be happy to work with you to add the functionality via SQANTI GTFs, though I must admit my my experience with python is limited.

**Comment by fairliereese** [comment]
Ah I was mostly wondering if you could provide me a sample SQANTI GTF that I could have to refer to. If you'd like, feel free to email me one at freese@uci.edu!
